### ISSUE TITLE
Unable to Dump Homebrew Sega Genesis Cart

### ISSUE THREAD

**Issue by lifewithmatthew** [retrostage/RetroBlaster#11]
I purchased a Homebrew Genesis game (Chip's Challenge) and when I go to dump it, it gives me an error of "Game showing invalid size of 1KB. Try cleaning the cartridge connector on your game and try again."

I double checked on my Sega to make sure the game was working and it is, and I tried dumping another sega cart (just to make sure I hadn't installed anything wrong) and it's working.

Is there a way to override and dump whatever it finds?

**Comment by retrostage** [comment]
What version of the RetroBlaster hardware are you using? Is it the RetroBlaster Mini or the RetroBlaster 2.0?

**Comment by lifewithmatthew** [comment]
Retroblaster 2.0

**Comment by retrostage** [comment]
It looks like a bug was introduced in software v2.2.0 that breaks the "Manual dump" button. I'll fix it in the next release. 

Until then, you can use software v2.1.6 to dump it. 

Check the "Manual Dump Size" box and enter the amount of ROM you want to dump. If you aren't sure what the game size is, enter "4096", as that is the largest possible ROM size for any standard game.

For some background, in case you're interested - a lot of homebrew/new games for Sega MD/GEN use a "template" ROM header. This template doesn't have a valid ROM size listed, and so for programs like the RetroBlaster that expect a valid ROM header to be there, it doesn't see an expected value and throws the error. In cases like this, the "Manual Dump size" method must be used.

**Comment by retrostage** [comment]
Fixed in v2.2.3 : https://github.com/retrostage/RetroBlaster/releases/tag/v2.2.3
