### ISSUE TITLE
NES/FC Dumping Not Working At All

### ISSUE THREAD

**Issue by TorqueEmPup** [retrostage/RetroBlaster#16]
I've tried multiple games that have been thoroughly cleaned, Auto Dump will not recognize the games, and manual dumping creates a bad dump that just gives a grey screen in an emulator.

Using the Retroblaster 2.0c Hardware, with 2.8d firmware, on 2.2.4 Software

**Comment by retrostage** [comment]
Do you have the voltage switch on the RetroBlaster set to 5V?

**Comment by TorqueEmPup** [comment]
Yes I do

**Comment by retrostage** [comment]
Can you email some of the dumps you've made to support@retrostage.net? It might shed some light on what is happening on your end.

Please include some pictures of your RetroBlaster unit, as well as a picture showing how you're inserting the cartridge into the adapter.

**Comment by TorqueEmPup** [comment]
All the pins are inserted into the programmer, don't see anything bad solder joints on the adapter.
I've included a few different manual dumps, one of each of the following cart types. MMC3, MMC1, UNROM, and NROM
![20241130_155117](https://github.com/user-attachments/assets/11669ce1-39b0-42a6-9465-6d5a969b2b5d)
![20241130_155435](https://github.com/user-attachments/assets/68328add-c4b8-479c-a653-fb373aa9ffd0)
[testdumps.zip](https://github.com/user-attachments/files/17966921/testdumps.zip)

**Comment by TorqueEmPup** [comment]
Another thing I JUST noticed after leaving the programmer and cartridge adapter plugged in is the main ASIC on the programmer is getting warm to the touch.

Not hot, but warm. This doesn't seem normal, as it doesn't get warm when other cartridge adapters are plugged in.

Maybe this is a fault with the adapter itself? I don't see any shorts on the adapter, so I am kinda at a loss.

**Comment by TorqueEmPup** [comment]
Email, sent.

**Comment by TorqueEmPup** [comment]
Ok, issue is fixed. 
Wasn't a software issue but an issue with one of the pins bridging to ground on the cart connector adapter.
