### ISSUE TITLE
Can't write games not divisible by 131072 bytes

### ISSUE THREAD

**Issue by thefrontbottoms247** [retrostage/RetroBlaster#3]
Using update 2.1.1

**Comment by retrostage** [comment]
I need more info. What game and what system was it for?

Generally it means you have an odd ROM size which is common in bad or corrupt ROM dumps.

**Comment by thefrontbottoms247** [comment]
Game is 'Goomba V2.2 - Pokemon Black - Special Palace Edition 1 by MB Hacks (Red Hack)', for the GBA. The file size is 1067kb. I was under the impression that the file size is okay given the recent update, being that GBA roms no longer were required to be a 2, 4, etc Mb integer value to write to a cartridge

**Comment by retrostage** [comment]
It allows any increment of 131072 bytes (128KBytes) to cover the "non-standard" sizes - I figured that would cover most games as most homebrew and hacks fit in that expectation. I'll check into adding auto-padding for weird game sizes.

**Comment by retrostage** [comment]
This should now be fixed as of version 2.1.2.
