### ISSUE TITLE
Non-Windows version of the software?

### ISSUE THREAD

**Issue by euan-forrester** [retrostage/RetroBlaster#4]
Would it be possible to port the RetroBlaster software to run on non-Windows machines, eg Mac? As a Mac user, it's definitely a bummer to have to reboot my machine into Windows every time I want to use the programmer (and once the Intel Macs go away completely, it won't be possible anymore).

Would it even be possible to use WebUSB to connect to the programmer? That way a webpage could be made instead of downloading the software, and any computer that can run Chrome could use it. https://web.dev/usb/

Thanks for making an awesome device!

**Comment by retrostage** [comment]
I'm wary of WebUSB due to security issues that could arise, so I don't want to go that route right now.

I do plan on porting this to Python so that Linux/Mac users can use it, just have to find the time to do it.

**Comment by euan-forrester** [comment]
Fair enough! I didn't realize there were security issues with webusb until googling it after you mentioned it.

A python version sounds like a good compromise though -- thank you and I'm glad it's somewhere on the horizon!
