### ISSUE TITLE
RetroBlaster Mini - open issues

### ISSUE THREAD

**Issue by retrostage** [retrostage/RetroBlaster#8]
Reports of some NES/FC games that use discrete mappers (CNROM, UNROM, etc) may not dump correctly with the RetroBlaster Mini at this time. 

There isn't any consistency with reports, but some games may not dump correctly from certain copies of the game, but dump perfectly fine with others. This is still being looked into.

List games that aren't dumping correctly here.

--- this may be fixed already as of software v2.2.2, need confirmation ---

**Comment by rpierucci** [comment]
I'm having issues dumping Paper Mario Saves on N64. It uses Flashram. The programmer dumps the save but theres never anything on it. I can actually pull the cart and dump with nothing plugged in and the dumper doesnt give any kind of error either, just dumps a blank file. 

EDIT: Can't get it to write either. Created a new .fla file in an emulator, created some saves. It writes a blank file back to the cart. No issues dumping the rom itself.

**Comment by retrostage** [comment]
Is your copy of the game original? Reproductions of games that use FlashRAM don't work with any RetroBlaster model at this time, something to do with how the cart is emulating the FlashRAM functionality.

**Comment by rpierucci** [comment]
Well dang it should be. Always thought it was. Let me open it up in a bit
and see what I find. Thanks for letting me know.

**Comment by rpierucci** [comment]
Hey, I just checked mine and it appears legit. It matches the right cart on this thread:

https://www.reddit.com/r/n64/comments/rs2yj4/side_by_side_comparison_of_a_repro_paper_mario/

Is there anything else I should try and check? Do you have a Paper Mario working? I could even send you this copy so you could do some testing if that would help. 

Another link matching mine: https://www.reddit.com/r/nintendo64/comments/mj2baa/will_someone_plz_confirm_i_didnt_just_buy_a_repro/

**Comment by retrostage** [comment]
I'll check into it. It's been verified that others like Zelda Majora's Mask and Jet Force Jemini both work, and they both use FlashRAM as well.

Have you verified that the game saves normally on an N64 console? Just so we know it's not a faulty chip and we're chasing ghosts :)

**Comment by rpierucci** [comment]
Yes I did. Actually had a 9 hr save I tried to back up and lost. But my fault I should have never written back to the cart lol. Gives me a reason to play it again with my kid anyways.

**Comment by retrostage** [comment]
Can you email RetroStage support the first few dump attempts you made for
it? I want to see what is in the hex data, if anything.

**Comment by rpierucci** [comment]
Will do!

**Comment by retrostage** [comment]
As I mentioned in my email @rpierucci , FlashRAM and SRAM games actually require byte-swapping the data before they will work on an emulator. This information was missing from the RetroBlaster Mini Wiki, but has now been added to avoid future confusion. Thank you for bringing it to my attention!

Relevant info [here](https://github.com/retrostage/RetroBlaster/wiki/RetroBlaster-Mini#n64-adapter-tab)

**Comment by lhathcock** [comment]
I'm having issues dumping the Flash memory from two of my GBA carts - Pokemon LeafGreen (US Rev 1) and Super Mario Advance 4 - SMB3 (US Rev 1). Both give me this error: "Flash type not recognized. Flash ID error: 09C2"

I noticed that both these games apparently can have two different Flash chips, maybe that's it? My dumps of the games themselves from both are fine.

**Comment by retrostage** [comment]
The Flash ID is correct but the bytes are backwards... weird. Do you have any other games that use Flash saves that dump the Flash OK?

**Comment by lhathcock** [comment]
Yep, I actually went through all the rest (15-ish titles), and while I haven't verified their contents, they all dumped fine.

EDIT: Just checked, saves seem fine using them in mGBA. Only ones I'm not totally sure on are Sonic Advance 2/3, because I pretty much haven't really played those on these carts. I'm guessing they're fine too.

**Comment by lhathcock** [comment]
The games:
- Advance Wars 1/2
- Final Fantasy Tactics Advance
- Golden Sun 1/2
- Mario Kart Super Circuit
- Mario vs. Donkey Kong
- Robopon 2: Cross Version
- Sonic Advance 1/2/3/Battle
- Sword of Mana
- Super Robot Taisen - OG2
- Tactics Ogre: The Knight of Lodis

**Comment by retrostage** [comment]
Great info, thanks! I'll check it out tomorrow

**Comment by retrostage** [comment]
created a ticket for this here #10

**Comment by lhathcock** [comment]
Would it be better for me to create separate tickets if I come across anything else, or put it here? Wasn't sure which one you preferred.

**Comment by retrostage** [comment]
Honestly separate tickets would be best, I'll probably close this ticket
soon so it doesn't become a jumbled mess.

**Comment by retrostage** [comment]
I've done some changes to the software @lhathcock , can you test the latest build (v2.2.2a) and see if that allows correctly dumping and/or writing to those GBA games that were giving the Flash ID error? Test the dumps in an emulator if you can so that we know they're working.

Latest build: https://github.com/retrostage/RetroBlaster/releases/tag/v2.2.2a

**Comment by lhathcock** [comment]
They dump, but they don't work in mGBA.

**Comment by retrostage** [comment]
Can you email those dumps to support@retrostage.net? I want to see what the
data in them looks like.

**Comment by lhathcock** [comment]
Seems to be filtering email address on here, but sent to support email on website.

**Comment by retrostage** [comment]
I replied via email, and apparently GitHub doesn't like that when including email addresses, haha.

So, the data on your Mario Advance 4 is mostly good, except the first byte is being read twice so there is a byte offset throwing things off. I'm going to remove v2.2.2a from the releases as it seems to be a firmware timing issue. Stand by and I'll email you a test firmware you can try
