### ISSUE TITLE
Super Mario RPG save dumping

### ISSUE THREAD

**Issue by lhathcock** [retrostage/RetroBlaster#9]
Hi, I've gotten my RetroBlaster Mini in, and I really like it! I've been able to dump the ROM of Super Mario RPG, but the software hangs up trying to dump the SRAM. Not sure if maybe it's user error on my part.

Thanks!

**Comment by retrostage** [comment]
You're right, definitely crashes. 

I forgot to enable the clocks for dumping SRAM, which means when it reads from a SA-1 game like Mario RPG it only sees garbage data.

This will be fixed in the next update!

**Comment by lhathcock** [comment]
Sounds great to me! I've certainly got plenty to dump in the meantime, haha. Thanks much!

**Comment by retrostage** [comment]
Hi @lhathcock , this issue should now be resolved in [v2.2.2 release](https://github.com/retrostage/RetroBlaster/releases/tag/v2.2.2)

**Comment by lhathcock** [comment]
Awesome, will give it a try this evening. Thanks very much!
